import type { AppUser, Category, MenuItem, OpeningHour, Order, ThemeSettings } from './types';

export const categories: Category[] = [
  { id: 'signature', name: { en: 'Signature Bowls', de: 'Signature Bowls' }, sortOrder: 1 },
  { id: 'desserts', name: { en: 'Desserts', de: 'Desserts' }, sortOrder: 2 },
  { id: 'drinks', name: { en: 'Drinks', de: 'Getranke' }, sortOrder: 3 },
  { id: 'brunch', name: { en: 'Brunch', de: 'Brunch' }, sortOrder: 4 },
  { id: 'offers', name: { en: 'Offers', de: 'Angebote' }, sortOrder: 5 },
];

export const menuItems: MenuItem[] = [
  {
    id: 'berry-cloud',
    categoryId: 'signature',
    name: { en: 'Berry Cloud Pancakes', de: 'Berry Cloud Pancakes' },
    description: { en: 'Mini pancakes, strawberry cream, berries, and white chocolate.', de: 'Mini-Pancakes, Erdbeercreme, Beeren und weisse Schokolade.' },
    price: 8.5,
    badge: { en: 'Popular', de: 'Beliebt' },
    imageStyle: 'berry',
    available: true,
    sortOrder: 1,
  },
  {
    id: 'lavender-waffle',
    categoryId: 'signature',
    name: { en: 'Lavender Honey Waffle', de: 'Lavendel-Honig-Waffel' },
    description: { en: 'Crisp waffle with lavender honey, vanilla cream, and almonds.', de: 'Knusprige Waffel mit Lavendelhonig, Vanillecreme und Mandeln.' },
    price: 9.25,
    badge: { en: 'New', de: 'Neu' },
    imageStyle: 'lavender',
    available: true,
    sortOrder: 2,
  },
  {
    id: 'pink-dream',
    categoryId: 'signature',
    name: { en: 'Pink Dream Crepe', de: 'Pink Dream Crepe' },
    description: { en: 'Soft crepe, rose sauce, pistachio crunch, and seasonal fruit.', de: 'Crepe mit Rosensauce, Pistazien-Crunch und Saisonfrucht.' },
    price: 7.75,
    imageStyle: 'pink',
    available: true,
    sortOrder: 3,
  },
  {
    id: 'lotus-jar',
    categoryId: 'desserts',
    name: { en: 'Lotus Cheesecake Jar', de: 'Lotus Cheesecake Glas' },
    description: { en: 'Layered cheesecake cream with biscuit crumble and caramel.', de: 'Cheesecake-Creme mit Keks-Crumble und Karamell.' },
    price: 6.75,
    badge: { en: 'Best seller', de: 'Bestseller' },
    imageStyle: 'caramel',
    available: true,
    sortOrder: 1,
  },
  {
    id: 'mochi-box',
    categoryId: 'desserts',
    name: { en: 'Mochi Box', de: 'Mochi Box' },
    description: { en: 'Six soft mochi bites: mango, matcha, vanilla, and berry.', de: 'Sechs Mochi: Mango, Matcha, Vanille und Beere.' },
    price: 10,
    imageStyle: 'mochi',
    available: true,
    sortOrder: 2,
  },
  {
    id: 'rose-milk',
    categoryId: 'drinks',
    name: { en: 'Rose Milk Cooler', de: 'Rosenmilch Cooler' },
    description: { en: 'Iced milk, rose syrup, basil seeds, and cream foam.', de: 'Eismilch, Rosensirup, Basilikumsamen und Cremeschaum.' },
    price: 4.5,
    imageStyle: 'drink-pink',
    available: true,
    sortOrder: 1,
  },
  {
    id: 'iced-matcha',
    categoryId: 'drinks',
    name: { en: 'Iced Strawberry Matcha', de: 'Iced Strawberry Matcha' },
    description: { en: 'Ceremonial matcha poured over strawberry milk.', de: 'Matcha auf Erdbeermilch.' },
    price: 5.25,
    imageStyle: 'matcha',
    available: true,
    sortOrder: 2,
  },
  {
    id: 'avo-toast',
    categoryId: 'brunch',
    name: { en: 'Avocado Brioche Toast', de: 'Avocado Brioche Toast' },
    description: { en: 'Toasted brioche, avocado, feta, chili oil, and herbs.', de: 'Brioche, Avocado, Feta, Chiliol und Krauter.' },
    price: 8.25,
    imageStyle: 'green',
    available: true,
    sortOrder: 1,
  },
  {
    id: 'combo',
    categoryId: 'offers',
    name: { en: 'Sweet Date Combo', de: 'Sweet Date Combo' },
    description: { en: 'Two desserts and two drinks for a shared table.', de: 'Zwei Desserts und zwei Getranke zum Teilen.' },
    price: 22,
    badge: { en: 'Save 15%', de: '15% sparen' },
    imageStyle: 'combo',
    available: true,
    sortOrder: 1,
  },
];

export const initialOrders: Order[] = [
  {
    id: 'SP-1042',
    customerName: 'Mia Carter',
    phone: '+49 151 000 2026',
    notes: 'No nuts, please.',
    lines: [{ item: menuItems[0], quantity: 2 }, { item: menuItems[5], quantity: 1 }],
    total: 21.5,
    status: 'new',
    createdAt: 'Today, 14:20',
  },
  {
    id: 'SP-1041',
    customerName: 'Jonas Weber',
    phone: '+49 152 441 901',
    notes: 'Table 6',
    lines: [{ item: menuItems[3], quantity: 1 }],
    total: 6.75,
    status: 'preparing',
    createdAt: 'Today, 13:58',
  },
];

export const users: AppUser[] = [
  { id: 'u1', name: 'Ava Reed', email: 'ava@sweezypop.test', role: 'admin', restaurant: 'Sweezypop HQ', active: true },
  { id: 'u2', name: 'Lena Frost', email: 'lena@sweezypop.test', role: 'owner', restaurant: 'Sweezypop Mitte', active: true },
  { id: 'u3', name: 'Noah Stein', email: 'noah@sweezypop.test', role: 'owner', restaurant: 'Sweezypop West', active: false },
];

export const defaultTheme: ThemeSettings = {
  primary: '#ff7eb6',
  accent: '#20c7b5',
  lavender: '#b9a4ff',
  background: '#fff7fb',
  surface: '#ffffff',
  text: '#211b33',
  mutedText: '#756a80',
  buttonText: '#ffffff',
  card: '#ffffff',
  border: '#eadff0',
  siteName: 'Sweezypop',
  logoText: 'Sweezypop',
  logoUrl: '',
  menuUrl: import.meta.env.VITE_MENU_PUBLIC_URL || 'https://sweezypop.vercel.app',
};

export const openingHours: OpeningHour[] = [
  { day: 'Monday', open: '10:00', close: '22:00', enabled: true },
  { day: 'Tuesday', open: '10:00', close: '22:00', enabled: true },
  { day: 'Wednesday', open: '10:00', close: '22:00', enabled: true },
  { day: 'Thursday', open: '10:00', close: '23:00', enabled: true },
  { day: 'Friday', open: '10:00', close: '00:00', enabled: true },
  { day: 'Saturday', open: '09:00', close: '00:00', enabled: true },
  { day: 'Sunday', open: '09:00', close: '21:00', enabled: true },
];
